[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && python app.py"

[[services]]
name = "web"
run = "cd server && python app.py"

# Use Python 3.9 instead of 3.8 - more widely available
[build.env]
PYTHON_VERSION = "3.9"