[build]
builder = "nixpacks"

[[services]]
name = "backend"
rootDir = "./server"
commands = [
  "pip install -r requirements.txt"
]

[[services]]
name = "frontend" 
rootDir = "./client"
commands = [
  "npm install",
  "npm run build"
]