[build]
builder = "dockerfile"
dockerfilePath = "./server/Dockerfile"

[[services]]
name = "backend"
sourcePath = "./server"

[[services]]
name = "frontend"
rootDir = "./client"
startCommand = "npm run start"
buildCommand = "npm install && npm run build"