[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://skillswap-production-0e78.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200